### ISSUE TITLE
oracle  to mysql  ddl problems

### ISSUE THREAD

**Issue by wakaka2019** [qlangtech/tis#105]
1、oracle number column changed to tinytext in mysql ,this will cause create table failed,it should be bigint or decimal
2、auto generated mysql ddl,it lacks a comma before "primary key" keyword

**Comment by baisui1981** [comment]
oracle -> mysql
![25F5AABA-FCEE-478D-AE7A-A91B9031A344](https://user-images.githubusercontent.com/21274618/156503878-3b29ef55-ac29-4416-9543-b060f6eb3d2b.png)

**Comment by baisui1981** [comment]
complete
