### ISSUE TITLE
Mysql 到Starrocks 做增量同步时，没有增量续传的功能

### ISSUE THREAD

**Issue by alex211a** [qlangtech/tis#108]
Mysql 到Starrocks 做增量同步时，没有增量续传的功能，比如某一时刻同步异常了，这时候没法接着上次同步，希望增加一个续传的点，可以接着binlog 继续同步。

**Comment by baisui1981** [comment]
嗯 ，在下一个版本中，会开通flink checkpoint功能，这样就会依赖于flink-cdc的operator state中记录的mysql binlog消费偏移量，恢复时自动从记录的偏移量开始消费

**Comment by baisui1981** [comment]
启用了flink checkpoint功能
