### ISSUE TITLE
Tis-flink 系统奔溃之后，之前的同步任务丢失了

### ISSUE THREAD

**Issue by alex211a** [qlangtech/tis#109]
有一次碰到了增量同步的异常，这时候 job 任务都没有了，重启服务之后也没有，希望这块当前任务有个存储，这样可以快速恢复同步

**Comment by baisui1981** [comment]
嗯，这个问题是和 https://github.com/qlangtech/tis/issues/108 一样的

**Comment by baisui1981** [comment]
complete
