### ISSUE TITLE
TIs mysql的sink端插件暂未支持

### ISSUE THREAD

**Issue by liufu1986007** [qlangtech/tis#110]
1、TIs mysql的sink端插件暂未支持
2、如何快速适配最新版本的flink、flink-cdc等流行插件版本？

**Comment by baisui1981** [comment]
1. 网上找了一个实例，看起来还算简单 https://blog.csdn.net/xianpanjia4616/article/details/88762069?utm_term=flink%E5%AE%9E%E7%8E%B0mysqlsink&utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~sobaiduweb~default-2-88762069&spm=3001.4430
2. flink 版本需要升级

**Comment by baisui1981** [comment]
https://github.com/DTStack/chunjun/blob/v1.12.2/flinkx-connectors/flinkx-connector-mysql/src/main/java/com/dtstack/flinkx/connector/mysql/sink/MysqlSinkFactory.java

**Comment by baisui1981** [comment]
已经利用chunjun实现了
