### ISSUE TITLE
MySQL增量同步到clickhouse带有dateTime字段存在问题

### ISSUE THREAD

**Issue by liufu1986007** [qlangtech/tis#116]
MySQL增量同步到clickhouse带有dateTime字段存在问题
![image](https://user-images.githubusercontent.com/15246761/164155419-f0c9879c-f31f-412f-b262-da8c057cd3e8.png)

**Comment by liufu1986007** [comment]
CREATE TABLE `as_alarm_type`  (
  `id` bigint NOT NULL COMMENT '类型标识',
  `category_id` bigint NULL DEFAULT 0 COMMENT '类别标识',
  `name` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '类型名称',
  `sort` int NULL DEFAULT NULL COMMENT '排序',
  `create_user` bigint NULL DEFAULT NULL COMMENT '创建人',
  `create_dept` bigint NULL DEFAULT NULL COMMENT '创建部门',
  `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间 ',
  `update_user` bigint NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '修改时间',
  `status` tinyint NULL DEFAULT NULL COMMENT '状态\r\n            ',
  `is_deleted` tinyint NULL DEFAULT 0 COMMENT '是否已删除',
  `tenant_id` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '租户id',
  `code` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'code编码',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '类型' ROW_FORMAT = DYNAMIC;


INSERT INTO `as_alarm_type` VALUES (1002, 1, '抽烟', NULL, NULL, NULL, '2021-09-27 09:54:32', NULL, NULL, NULL, 0, '111111', '111');

**Comment by baisui1981** [comment]
Complete
