### ISSUE TITLE
Flink Cluster 单机版启动报错

### ISSUE THREAD

**Issue by smileLuckBoy** [qlangtech/tis#124]
http://tis.pub/docs/install/flink-cluster/standalone/ 启动报错
![image](https://user-images.githubusercontent.com/8327780/169225298-c09c1162-5cbd-4c94-8662-baf47ea2636e.png)

**Comment by baisui1981** [comment]
由于tis-uber v3.5 与 tis-flink v3.4 版本不一致造成的
