### ISSUE TITLE
TIS 增量同步很慢，一个表需要10秒+多以上才能处理完，希望优化下这个速度

### ISSUE THREAD

**Issue by alex211a** [qlangtech/tis#126]
TIS 增量同步很慢，一个表需要10秒+多以上才能处理完，希望优化下这个速度

**Comment by baisui1981** [comment]
兄弟 把日志贴一下呗

**Comment by alex211a** [comment]
![image](https://user-images.githubusercontent.com/96170269/169951132-3066b6fa-c418-48d4-99c2-20eb420f1a84.png)


![image](https://user-images.githubusercontent.com/96170269/169950803-0a4074c2-e5cc-4ddd-ae7b-5221cd980364.png)

**Comment by baisui1981** [comment]
收到，这个会优化的

**Comment by baisui1981** [comment]
已经优化了
