### ISSUE TITLE
编译失败～求解答～非常感谢

### ISSUE THREAD

**Issue by 805094591** [qlangtech/tis#142]
Could not transfer artifact com.alibaba.datax:datax-config:pom:3.6.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [rdc-releases (http://mvn-repo.oss-cn-hangzhou.aliyuncs.com/release/, default, releases), rdc-snapshots (http://mvn-repo.oss-cn-hangzhou.aliyuncs.com/snapshot/, default, snapshots)]

**Comment by 805094591** [comment]
![a1](https://user-images.githubusercontent.com/39234160/192990032-60bedef5-f6cc-4b05-bbb5-3ccaa98b72eb.png)

**Comment by baisui1981** [comment]
can you make command ping available 
`ping mvn-repo.oss-cn-hangzhou.aliyuncs.com`
