### ISSUE TITLE
macOS 13.0.1 根据文档安装报错

### ISSUE THREAD

**Issue by jsrgqinbin** [qlangtech/tis#165]
macOS 13.0.1 根据文档安装报错

https://tis.pub/docs/install/tis/uber

根据单节点安装的文档安装

./bin/tis start
working dir:/Users/Ben/Downloads/tis-uber
start web-start successed pid is 44746 
sed: 1: "/Started/Q": invalid command code Q

报错如上

**Comment by baisui1981** [comment]
mac 上 是有这个问题，不过进程是正常启动了。后续再优化一下
