### ISSUE TITLE
自动生成的querysql语句增加了"`CURRENT_CONNECTIONS`",                "`TOTAL_CONNECTIONS`"等字段

### ISSUE THREAD

**Issue by bibichuan** [qlangtech/tis#172]
嗯嗯，自动建表语句没有错，但是不知道为什么datax的语句多了 "`CURRENT_CONNECTIONS`",  "`TOTAL_CONNECTIONS`",

**Comment by bibichuan** [comment]
"querySql":[

                  "SELECT `USER`,`CURRENT_CONNECTIONS`,`TOTAL_CONNECTIONS`,`username`,`password`,`enabled` FROM users "

                ]，表名为user表

**Comment by baisui1981** [comment]
mysql8会有这样的情况 https://blog.csdn.net/weixin_42134117/article/details/113280299
示例数据库：https://gitee.com/y_project/RuoYi-Cloud/raw/master/sql/ry_config_20220929.sql

**Comment by bibichuan** [comment]
感谢您的来信，敝人已收到。敝人会尽快给您回复，谢谢。
