### ISSUE TITLE
[feature]批量构建添加增量同步的需求

### ISSUE THREAD

**Issue by tirestay** [qlangtech/tis#187]
比如以ID或者修改时间为参考点，同步后保存最新的点，下一次批量构建从保存点往后开始同步。

**Comment by baisui1981** [comment]
这个需求有两个前提，
1. 每个表上必须要有一个timestamp类型的保存记录更新的时间戳字端，用以每次从source 端加载更新的记录
2. sink端的数据必须要支持upset或者replace操作

不过这个类型的操作，TIS中其实已经有了，选择chunjun类型的source端就是基于这个时间轮询筛选出更新记录来执行增量同步的
