### ISSUE TITLE
介意支持下Windows么？

### ISSUE THREAD

**Issue by KnightBlood** [qlangtech/tis#191]
虽然把tis这个shell脚本用bat重写一下就好 
但是我觉得这玩意还得时官方做比较靠谱

**Comment by baisui1981** [comment]
能把你写的 bat 脚本 贡献一下不？

**Comment by KnightBlood** [comment]
> 能把你写的 bat 脚本 贡献一下不？

我直接敲cmd 启动web-start.jar的

**Comment by KnightBlood** [comment]
java  -Xms2G -Xmx3G -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -XX:ParallelGCThreads=4 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=utf-8 -Dtis.launch.port=8080 -DnotFetchFromCenterRepository=true -Ddata.dir=../data -Dlog.dir=../logs -Dweb.root.dir=../  -Xrunjdwp:transport=dt_socket,address=50000,suspend=n,server=y -jar web-start.jar

> > 能把你写的 bat 脚本 贡献一下不？
> 
> 我直接敲cmd 启动web-start.jar的

java  -Xms2G -Xmx3G -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -XX:ParallelGCThreads=4 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=utf-8 -Dtis.launch.port=8080 -DnotFetchFromCenterRepository=true -Ddata.dir=../data -Dlog.dir=../logs -Dweb.root.dir=../  -Xrunjdwp:transport=dt_socket,address=50000,suspend=n,server=y -jar web-start.jar

类似于这样

**Comment by baisui1981** [comment]
这貌似是单薄了一点，不过能用就行
