### ISSUE TITLE
task-reactor 1.5版本依赖在maven中央仓库已不可见.打包不成功

### ISSUE THREAD

**Issue by fengpiaoxue** [qlangtech/tis#206]
windows环境下,项目父pom.xml
<dependency>
                <groupId>org.jenkins-ci</groupId>
                <artifactId>task-reactor</artifactId>
                <version>1.5</version>
            </dependency>
依赖在maven中央仓库已不可见.打包不成功, 升级到1.6可以打包成功

**Comment by baisui1981** [comment]
您用的是TIS 最新的master 分支吗？ 正常来说应该不会，因为以下依赖是放置在`http://mvn-repo.oss-cn-hangzhou.aliyuncs.com/release/` 仓库中的，
``` xml
 org.jenkins-ci
task-reactor
1.5
```
你看看 本地maven是否配置了mirror，如果配置了mirror配置，请按照如下配置：
``` xml
    <mirrors>
        <mirror>
            <id>mirror</id>
            <mirrorOf>central</mirrorOf>
            <name>mirror</name>
           <url>https://maven.aliyun.com/repository/public</url>
        </mirror>
    </mirrors>
```
切忌 mirrorOf配置不要配置成 <mirrorOf>*</mirrorOf>
