### ISSUE TITLE
mysql_starrocks实时同步问题

### ISSUE THREAD

**Issue by fhrush** [qlangtech/tis#210]
从mysql到starrocks 同步以及实时同步的问题，有的数据库中就几张表，达不到40张的限制， 有的库中表为四十二张表 是否可以开发reader可以跨库的读取与写入了？

**Comment by fhrush** [comment]
因为为了某几张表不能跨库建一个实例，后面的flink也得启动一个job感觉有点亏了。

**Comment by baisui1981** [comment]
> 可以跨库的读取与写入了

这个执行方式是否可以具体说明一下
