### ISSUE TITLE
3.0，添加数据源按钮没有弹窗

### ISSUE THREAD

**Issue by EliLiu-YF** [qlangtech/tis#48]
![image](https://user-images.githubusercontent.com/69829859/142969966-8ea1cf49-e938-4814-8541-af8f05f858d4.png)

**Comment by baisui1981** [comment]
兄弟 别急 我正在加班加点搞 这两 天就能上线，这些问题 我都改了 ，现在还有几个小问题 ，稍安勿躁。可以加我一下微信：16660356

**Comment by baisui1981** [comment]
已经发布v3.1.0 [http://tis.pub/docs/install/uber/]( http://tis.pub/docs/install/uber/)
