### ISSUE TITLE
MySQL Reader missing

### ISSUE THREAD

**Issue by archongum** [qlangtech/tis#49]
MySQL plugin installed but MySQL Reader couldn't show up.

![image](https://user-images.githubusercontent.com/20929338/143173626-fd03845a-507b-47c8-9fa9-ae533cfeca66.png)

![image](https://user-images.githubusercontent.com/20929338/143173582-5dcacef1-0ba5-4cc0-a08c-519648e05b31.png)

**Comment by baisui1981** [comment]
兄弟 别急，从插件池里面加载插件的流程我正在优化，争取体验做得比jenkins要好。这两天就会发布，这个版本我是flink-cdc的实时增量同步也加进来了。

**Comment by baisui1981** [comment]
已经发布[ http://tis.pub/docs/install/uber/]( http://tis.pub/docs/install/uber/)
