### ISSUE TITLE
执行同步后期望postsql可以在目标服务器上执行分号分隔的多个sql

### ISSUE THREAD

**Issue by xddouble** [qlangtech/tis#59]
![e71f0b1322868bc87eccd549737898d](https://user-images.githubusercontent.com/1083908/146895505-5a1ede41-1f9d-460a-b043-ee28a8866b19.png)
执行同步后期望postsql可以在目标服务器上执行分号分隔的多个sql

**Comment by baisui1981** [comment]
这个功能先不支持了
