### ISSUE TITLE
全量同步很多表的时候（测试的时候 是100多张表），部分表成功，部分表不会同步

### ISSUE THREAD

**Issue by alex211a** [qlangtech/tis#60]
全量同步很多表的时候（测试的时候 是100多张表），部分表成功，部分表不会同步，希望能优化下

**Comment by baisui1981** [comment]
这个是因为单机版的 [TaskExec.java](https://github.com/qlangtech/plugins/blob/54c6a1e5141f20450a20291f614086820a02598f/tis-datax/tis-datax-local-executor/src/main/java/com/qlangtech/tis/plugin/datax/TaskExec.java) 的执行等待队列长度只有30，新版本里面会加到200的长度
``` java
    public static ExecutorService newFixedThreadPool(int nThreads) {
        return new ThreadPoolExecutor(nThreads, nThreads, 0L, TimeUnit.MILLISECONDS,
                new LinkedBlockingQueue<Runnable>(200),
                Executors.defaultThreadFactory());
    }
```
