### ISSUE TITLE
页面bug

### ISSUE THREAD

**Issue by name4ray** [qlangtech/tis#61]
![image](https://user-images.githubusercontent.com/95423235/147031484-5711486f-55e9-4ae4-b948-ed36a2b312d6.png)
新建通道生成的建表DDL文件 ，需要打开查看并编辑时，无法滚动展示全部内容，使用向下箭头挪到最下方后，”保存“按钮又无法显示
![image](https://user-images.githubusercontent.com/95423235/147031799-9ae0afea-8fc7-4925-ab22-e9f1d144e1ce.png)

**Comment by baisui1981** [comment]
嗯，收到，会尽快改一下的

**Comment by k4124k** [comment]
屏幕缩放下, 可以看到保存按钮, 临时解决方案

> ![image](https://user-images.githubusercontent.com/95423235/147031484-5711486f-55e9-4ae4-b948-ed36a2b312d6.png) 新建通道生成的建表DDL文件 ，需要打开查看并编辑时，无法滚动展示全部内容，使用向下箭头挪到最下方后，”保存“按钮又无法显示 ![image](https://user-images.githubusercontent.com/95423235/147031799-9ae0afea-8fc7-4925-ab22-e9f1d144e1ce.png)

**Comment by baisui1981** [comment]
v3.3.0中已经修复
