### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by bibichuan** [qlangtech/tis#64]
I installed 3.2.0 in the stand-alone version.When I created the instance and selected the data pipeline, an error occurred.

`IncompatibleClassChangeError:Method 'java.lang.String com.qlangtech.tis.datax.IDataxGlobalCfg.getDefaultTemplate()' must be InterfaceMethodref constant`

My jdk version is openjdk 13.

**Comment by baisui1981** [comment]
目前还没有使用openjdk 13测试过，要不先用`jdk1.8` 用一下

**Comment by bibichuan** [comment]
感谢您的来信，敝人已收到。敝人会尽快给您回复，谢谢。

**Comment by baisui1981** [comment]
> 感谢您的来信，敝人已收到。敝人会尽快给您回复，谢谢。

兄弟有用jdk1.8测试过吗？

**Comment by bibichuan** [comment]
1.8 测试了可以用的

**Comment by baisui1981** [comment]
> 1.8 测试了可以用的

谢谢支持，这个issue 我先关了哦
