### ISSUE TITLE
tis.sh 移除sh, 统一使用bash

### ISSUE THREAD

**Issue by k4124k** [qlangtech/tis#65]
alpine中启动tis.sh, 出错.
Zookeeper停止出错: Syntax error: "(" unexpected (expecting "fi")

**Comment by baisui1981** [comment]
收到，下一个版本会改的

**Comment by baisui1981** [comment]
可以借鉴：
* https://mp.weixin.qq.com/s/FMn4gbGxTh-bmnZ5cajBPA
* tomcat的启动脚本来改造：https://github.com/apache/tomcat/blob/main/bin/startup.sh

**Comment by baisui1981** [comment]
将 https://github.com/qlangtech/tis/issues/55 一并修改
