### ISSUE TITLE
未支持mysql json类型字段

### ISSUE THREAD

**Issue by k4124k** [qlangtech/tis#68]
rt

**Comment by baisui1981** [comment]
收到，关于json字段类型，我想扩展问一下，如sink导入到clickhouse 或者 doris/starrocks中需要作额外的按照key/value拆开处理吗？

**Comment by k4124k** [comment]
从olap和etl的需求来说, 需要json的解析及映射到目标表的字段

**Comment by baisui1981** [comment]
已经解决了只要mysql jdbc 驱动升级一下就行

**Comment by baisui1981** [comment]
v3.3.0中已经支持
