### ISSUE TITLE
添加数据管道报错

### ISSUE THREAD

**Issue by kengan** [qlangtech/tis#70]
具体运行环境
centos 7.9
openjdk 11
在界面点击添加管道报如下错误：
IncompatibleClassChangeError: Method 'java.lang.String com.qlangtech.tis.datax.IDataxGlobalCfg.getDefaultTemplate()' must be InterfaceMethodref constant

**Comment by baisui1981** [comment]
是否可以用jdk1.8 试验一下，TIS目前还没有进行openjdk 11 测试过

**Comment by bibichuan** [comment]
我也是遇到这个问题，我用的是openjdk 13

**Comment by baisui1981** [comment]
请大家先用jdk1.8，高版本支持要等等
