### ISSUE TITLE
必须由小写字母开头，数字、下划线、字母、减号结尾

### ISSUE THREAD

**Issue by bibichuan** [qlangtech/tis#71]
创建sqlserver数据源的时候，显示 ：“必须由小写字母开头，数字、下划线、字母、减号结尾”，但是我的数据库名是大写字母开头的，用其他的数据库链接工具可以允许大写字母开头的，能不能咱这个也支持大写字母开头呢？

**Comment by baisui1981** [comment]
数据库应该是 大小写不敏感的，如果在输入栏目将数据库写成小写的数据库能识别出吗？

**Comment by bibichuan** [comment]
![截图_选择区域_20211228100948](https://user-images.githubusercontent.com/14054904/147520166-b5f20b75-7ee2-4596-809c-9a13f2e56c8d.png) 用户名也不能大写字母开头，直接校验不通过，连不上。

**Comment by baisui1981** [comment]
嗯 ，收到，会在3.3.0 版本中修改

**Comment by baisui1981** [comment]
3.3.0 版本中已经修复

**Comment by bibichuan** [comment]
这个能不能不要限制数据库名称呢？老的数据库用了中文名作为数据名，使用jdbc连接的时候，可以通过，tis不通过
