### ISSUE TITLE
请问是否支持指定数据库模式

### ISSUE THREAD

**Issue by kengan** [qlangtech/tis#72]
我想将postgresql某个数据库中的数据导入到es，我使用了datax插件，但我的表不是在默认的public模式下，而是在test模式下，请问tis是否能支持模式设置，我尝试过在定义数据源的时候利用参数 searchpath 或者currentSchema均不成功，具体见如下连接
 jdbc:postgresql://localhost:5432/mydatabase?searchpath=test
 jdbc:postgresql://localhost:5432/mydatabase?currentSchema=test
请问tis在配置数据源的时候如何制定导入那个数据库模式的下的表，谢谢

**Comment by baisui1981** [comment]
目前 TIS 的PG数据源 只支持默认的`public`, 不过这个参数项目 会在下一个版本**3.3.0** 中加入，顺便问一下您的pg jdbc的驱动是用什么版本的？

**Comment by kengan** [comment]
@baisui1981 感谢的你回答， 我是直接利用tis插件库里面的datax pg插件来连接pg的，没有用额外的jdbc驱动

**Comment by baisui1981** [comment]
@kengan 已经在v3.3.0中将pg的 jdbc驱动升级到,并且支持 自定义schema选择

```xml
 <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.3.1</version>
        </dependency>
```
