### ISSUE TITLE
mysql to starrocks 中 blob 字段问题

### ISSUE THREAD

**Issue by alex211a** [qlangtech/tis#73]
mysql 源表中 如果有blob 字段 会导致同步失败，希望 blob 字段 映射成starrcoks 中的varchar，但是实际内容并不需要同步过来，希望同步不要报错就行

**Comment by baisui1981** [comment]
收到

**Comment by baisui1981** [comment]
如果是blob则为二进制类型，原则上是应该对应bitmap字段类型，需要导入的需要手动去修改SQLddl语句
