### ISSUE TITLE
mysql to starrocks  表结构变更希望同步

### ISSUE THREAD

**Issue by alex211a** [qlangtech/tis#74]
目前不支持表结构的变更同步，希望加上这块的功能，另外如果做不到的实时的变更，希望可以改完配置后，直接刷新一下就能变更，不需要再重新配置一遍。

**Comment by baisui1981** [comment]
现在ddl 没有像datax json 配置配置完成之后就重新自动生成一下的原因是，ddl脚本是可以生成之后 手动修改的，为了防止把手动修改的内容覆盖掉，所以就导致现在您描述的，需要在重新手动配置一下。

这个会专门加一个针对 ddl重新自动生成功能。

**Comment by baisui1981** [comment]
v3.3.0中已经修复
