### ISSUE TITLE
Flink实时同步到需要密码的es失败，401 Unauthorized

### ISSUE THREAD

**Issue by JanCong** [qlangtech/tis#76]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/16347506/147718518-88ed1b4f-42ed-4492-81be-b9492bb14276.png">

**Comment by baisui1981** [comment]
兄弟有两点需要确认一下
1. 这个flink使用的是 tis定制过的tis-flink?
2. 所谓的用户名密码应该就是accessKeyId和accessKeySecret 吧？

**Comment by JanCong** [comment]
> 兄弟有两点需要确认一下
> 
> 1. 这个flink使用的是 tis定制过的tis-flink?
> 2. 所谓的用户名密码应该就是accessKeyId和accessKeySecret 吧？

1.使用的是tis定制过的tis-flink
2. 用户名密码是accessKeyId和accessKeySecret

用的是阿里云的es，试了自建的不用验证的es是没用问题的

**Comment by baisui1981** [comment]
嗯 现在的确 没有把 accessKeyId和accessKeySecret  加入到认证的流程中去，下个版本**v3.4.0** 会把这个功能加入进去的

**Comment by baisui1981** [comment]
其他还有啥建议或者需求 都一并提过来

**Comment by baisui1981** [comment]
修改了https://github.com/qlangtech/plugins/blob/8f62200ba7f85d33d64308ab02ccefa96989f376/tis-incr/tis-sink-elasticsearch7-plugin/src/main/java/com/qlangtech/tis/plugins/incr/flink/connector/elasticsearch7/ElasticSearchSinkFactory.java#L176 ，当用户设置了 用户名和密码之后 ，会在这里将 用户认证信息加入的http的报头中去，明天再测试一下
