### ISSUE TITLE
使用DataX进行数据同步时，是否支持增量同步？

### ISSUE THREAD

**Issue by bibichuan** [qlangtech/tis#78]
在文档里面没有介绍，在使用DataX的时候，是否支持增量同步，如果我的一个数据库非常大，使用tis进行同步的时候，网络断掉了，或者数据库发生错误了，中间断掉了，再次运行的时候，是全量备份还是从断掉的数据开始呢？

**Comment by baisui1981** [comment]
1. 增量，目前是基于flink-cdc同步机制, 具体可以参考一下这个文章：http://tis.pub/docs/example/mysql-syn-starrocks/#%E5%AE%9E%E6%97%B6%E5%90%8C%E6%AD%A5%E5%BC%80%E9%80%9A
2.datax批量导入 目前还没有实现断点续传功能，如果在执行过程中意外中断，是需要重新跑的，不过这部分功能是可以实现的。
