### ISSUE TITLE
在配置DATAX  oracle reader 时，有大量重复字段出现

### ISSUE THREAD

**Issue by eversmily** [qlangtech/tis#81]

**Comment by baisui1981** [comment]
通过 https://github.com/qlangtech/tis/blob/77aa882c0e4f0d2ba900fe0495145307e41a83b4/tis-plugin/src/main/java/com/qlangtech/tis/plugin/ds/DataSourceFactory.java#L143  添加`addedCols`防止重复列添加

``` java 
final Set<String> addedCols = Sets.newHashSet()
```
