### ISSUE TITLE
Oracle数据库同步建表功能建议

### ISSUE THREAD

**Issue by name4ray** [qlangtech/tis#85]
1在同步源表到目标表时 如同步mysql 到doris  自动生成的建表语句没有COMMENT注释;
2在同步oracle库时，配置数据源后
![image](https://user-images.githubusercontent.com/95423235/148737948-12ee9ed4-ae03-45ee-aac8-845b9b47d117.png)
，在创建的实例中输入源只能看到 oracle用户的表空间，看不到分配了权限的其他表；

**Comment by baisui1981** [comment]
1. 同步的表中添加上COMMENT 这个打算是添加到扩展插件中，社区版的实现方案中，不提供COMMENT自动映射功能
2.能告知一下您的 oracle的具体版本不？我要在测试环境中回归一下

**Comment by baisui1981** [comment]
当前取用户名下的表是通过 `SELECT (TABLE_NAME) FROM user_tables` 语句得到的，你可以试试用**lin** 登录，执行该语句试试
如果系统管理员授权给该用户的表不在返回结果中，那说明，取得用户下的表，还要执行其他sql才能得到

**Comment by baisui1981** [comment]
按照 这个文档上列的语句 ：https://www.cnblogs.com/qlqwjy/p/8405478.html

是否应该使用 :

```sql
select * from all_tables where owner='TEST'；
```

**Comment by name4ray** [comment]
要用 select table_name,owner from all_tables  查出表和owner ，页面显示时要同时显示用户名和表名，避免不同用户同表名情况。不能加where owner='TEST'  加了就还是不能查出所有

**Comment by baisui1981** [comment]
> 要用 select table_name,owner from all_tables 查出表和owner ，页面显示时要同时显示用户名和表名，避免不同用户同表名情况。不能加where owner='TEST' 加了就还是不能查出所有

那oracle在抽取数据的时候 ，都要 select 语句的表名，上都要加上 owner? 例如： `owner.tablename`

**Comment by name4ray** [comment]
是的

**Comment by baisui1981** [comment]
明白了，`3.4.0` 版本里会修改的
