### ISSUE TITLE
实例ID限制字符输入

### ISSUE THREAD

**Issue by tututu123** [qlangtech/tis#92]
希望界面填写的实例ID放开减号（-）的输入。
![image](https://user-images.githubusercontent.com/17424962/149904409-da2786ff-0c48-458b-8d6e-ffd183d5e715.png)

**Comment by baisui1981** [comment]
AddAppAction.isAppNameValid() 方法中修改一下使用 
```java
return Validator.identity.validate(msgHandler, context, fieldKey, form.getProjectName());
```

**Comment by baisui1981** [comment]
不能放开这个限制，否则在增量脚本编译过程中会，由于会由名称映射成java类名导致编译不通过

**Comment by baisui1981** [comment]
comlete
